# Generated by Django 4.1.2 on 2022-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"verbose_name": "Чат", "verbose_name_plural": "Чаты"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["pub_date"],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterField(
            model_name="chat",
            name="chat_type",
            field=models.CharField(
                choices=[("DIALOG", "Dialog"), ("CHAT", "Chat")],
                max_length=6,
                verbose_name="Тип чата",
            ),
        ),
    ]
