# Generated by Django 4.1.2 on 2022-10-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_alter_chat_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
