# Generated by Django 4.1.2 on 2022-10-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_delete_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
