# Generated by Django 4.1.2 on 2022-10-25 15:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="myuser",
            name="height_field",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Высота иконки"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                height_field="height_field",
                null=True,
                upload_to=users.models.user_directory_path,
                verbose_name="Иконка пользователя",
                width_field="width_field",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="width_field",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Ширина иконки"
            ),
        ),
    ]
